name: Build and push containers

on:
  release:
    types: [published]

jobs:
  tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
    steps:
      - name: Compile tag list
        id: tags
        run: |
          PREFIX=ghrc.io/laminas/laminas-ci-matrix
          MAJOR="${PREFIX}:$(echo ${GITHUB_REF} | cut -d. -f1)"
          MINOR="${MAJOR}.$(echo ${GITHUB_REF} | cut -d. -f2)"
          PATCH="${PREFIX}:${GITHUB_REF}"
          echo "::set-output name=tags::${MAJOR}%0A${MINOR}%0A${PATCH}"

  release-container:
    runs-on: ubuntu-latest
    needs: [tags]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ needs.tags.outputs.tags }}

